name: Render CV
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rendercv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sinaatalay/rendercv@v0 # Fixed the action name here
        with:
          cv_file_path: Oscar_Ortega_CV.yaml
          gh_pages_branch: gh-pages
          force_orphan: true
